/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class AppAssets {
  static const String icPoster = "assets/images/ic_poster.png";
  static const String customImage1 = "assets/images/custom_image_1.png";
  static const String customImage2 = "assets/images/custom_image_2.png";
  static const String customImage3 = "assets/images/custom_image_3.png";
  static const String customImage4 = "assets/images/custom_image_4.png";
  static const String redRejected = "assets/images/red_rejected.png";
  static const String featherLoader = "assets/images/ic_loader.png";
  static const String icLoader = "assets/svg/svg_ic_loader.svg";
  static const String bulb = "assets/images/ic_bulb.png";
  static const String icBulb = "assets/svg/svg_ic_bulb.svg";
  static const String getStartedBg = "assets/images/get_started_bg.png";
  static const String gradientBottom = "assets/svg/gradient_bottom.svg";
  static const String selectedImage = "assets/images/selected_image.png";
  static const String svgAgriculture = "assets/svg/svg_agriculture.svg";
  static const String svgBack = "assets/svg/svg_back.svg";
  static const String svgBackGetStartedScreen = "assets/svg/svg_back_get_started_screen.svg";
  static const String svgBanking = "assets/svg/svg_banking.svg";
  static const String svgCyber = "assets/svg/svg_cyber.svg";
  static const String svgGallery = "assets/svg/svg_gallery.svg";
  static const String svgGrocery = "assets/svg/svg_grocery.svg";
  static const String svgHardware = "assets/svg/svg_hardware.svg";
  static const String svgMedical = "assets/svg/svg_medical.svg";
  static const String svgMore = "assets/svg/svg_more.svg";
  static const String svgPrachar = "assets/svg/svg_prachar.svg";
  static const String svgMobile = "assets/svg/svg_mobile.svg";
  static const String svgNext = "assets/svg/svg_next.svg";
  static const String svgOther = "assets/svg/svg_other.svg";
  static const String svgPrinting = "assets/svg/svg_printing.svg";
  static const String svgRestaurant = "assets/svg/svg_restaurant.svg";
  static const String svgRightArrow = "assets/svg/svg_right_arrow.svg";
  static const String svgStationary = "assets/svg/svg_stationary.svg";
  static const String svgTravel = "assets/svg/svg_travel.svg";
  static const String svgDownload = "assets/svg/download.svg";
  static const String svgFacebook = "assets/svg/facebook.svg";
  static const String svgShare = "assets/svg/share.svg";
  static const String svgWhatsapp = "assets/svg/whatsapp.svg";
  static const String svgYoutube = "assets/svg/svg_youtube.svg";

  ///Fonts
  static const String robotoBold = "assets/fonts/Roboto-Bold.ttf";
  static const String robotoMedium = "assets/fonts/Roboto-Medium.ttf";
  static const String robotoRegular = "assets/fonts/Roboto-Regular.ttf";

  ///Lottie
  static const String lottieParticals = "assets/lottie/particals.json";
  static const String lottieSuccess = "assets/lottie/success_tu.json";
}
